### ISSUE TITLE
Support uploading backups to multiple destinations at a time

### ISSUE THREAD

**Issue by weak-head** [weak-head/nimbus#19]
### Description

tbd

### Proposed Configuration Changes

```yaml
commands:
  backup:
    destination: /mnt/backups
    archive: rar
    upload: 
      - aws_archival
      - gcp_store
    directories:
      apps:
        - /mnt/ssd/apps/gitlab
```
