### ISSUE TITLE
Support notifications via emails

### ISSUE THREAD

**Issue by weak-head** [weak-head/nimbus#3]
### Description

Similar to discord notifications, the operation report and status notification should be sent via emails.

### Configuration changes

```yaml
observability:
  notifications:
    email:
      host: email-smtp.eu-central-1.amazonaws.com
      port: 587
      encryption: tls
      username: user
      password: SecretPassword
```
