### ISSUE TITLE
Configurable backup and upload names, directories and keys

### ISSUE THREAD

**Issue by weak-head** [weak-head/nimbus#5]
### Description

For some particular use cases we need to support different rules for custom backup and upload key naming.

### Changes

As an option, replace the way how destination path is composed.
Right now, the following method is used:

```py
def _compose_path(self, destination: str, group: str, folder: str, today: datetime) -> str:
    pass
```

It should be replaced with a [Strategy](https://en.wikipedia.org/wiki/Strategy_pattern) that is injected into Backup command.

The possible extension could include a configurable smart Strategy per a particular backup entry.

Proposed changes to the config:

**Simplified short:**
```yaml

backup:
  destination: /mnt/backups
  archive: rar-protected
  upload: aws-archive
  directories: 
    apps:
      - /mnt/ssd/apps/gitlab
      - /mnt/ssd/apps/nextcloud
      - /mnt/ssd/apps/plex
```

**Expanded complete:**
```yaml

backup:
  destination: /mnt/backups
  archive: rar-protected
  upload: aws-archive
  directories: 
    apps:
      - path: /mnt/ssd/apps/gitlab
        backup: gitlab/gitlab.{ext} # backup path
        upload: apps/gitlab.{ext}   # upload key
      - /mnt/ssd/apps/nextcloud
      - /mnt/ssd/apps/plex
```

**Comment by weak-head** [comment]
Consider alternative approach with a template path for a destination:

```yaml
commands:
  backup:
    destination: "/mnt/backups/{group}/{folder_name}/{folder_name}_{datetime}.{ext}"
    archive: rar_protected
    upload: aws_archival
    directories:
      apps:
        - /mnt/ssd/apps/plex
      media:
        - /mnt/hdd/music
      photos:
        - path: /mnt/hdd/photos/2024
           destination: "/mnt/backups/photos/{folder_name}.{ext}"
```
