### ISSUE TITLE
Create operation report in PDF format

### ISSUE THREAD

**Issue by weak-head** [weak-head/nimbus#7]
### Description

Support PDF format for report generation.

### Configuration changes

The `observability.reports.format` key could accept `pdf` value:

```yaml
observability:
  reports:
    format: pdf
    directory: ~/.nimbus/reports
```
