### ISSUE TITLE
Add zfs snapshot management command

### ISSUE THREAD

**Issue by weak-head** [weak-head/nimbus#8]
### Description

Add support of `ni snapshot` command, that creates and rotates [ZFS snapshots](https://docs.oracle.com/cd/E19253-01/819-5461/gbciq/index.html).

### Configuration changes

Below are proposes configuration changes.

```yaml
commands:
  snapshot:
    keep:
      most_recent: 3
    datasets:
      - data/services/cloud
      - data/services/gitlab
```
